UPDATE PERSONAGENS SET NOME_PERSONAGEM = 'Fer7' WHERE ID_PERSONAGEM = '3'

UPDATE CLASSES SET NOME_CLASSE = 'Necromancer' WHERE ID_CLASSE = '5'

SELECT * FROM PERSONAGENS

SELECT * FROM CLASSES

SELECT NOME_CLASSE FROM CLASSES

SELECT * FROM HABILIDADES

SELECT COUNT(*) FROM HABILIDADES

SELECT ID_HABILIDADE FROM HABILIDADES ORDER BY ID_HABILIDADE ASC

SELECT * FROM TIPO_HABILIDADES

SELECT * FROM HABILIDADES
INNER JOIN TIPO_HABILIDADES ON HABILIDADES.ID_TIPO = TIPO_HABILIDADES.ID_TIPO

SELECT * FROM PERSONAGENS 
INNER JOIN CLASSES ON CLASSES.ID_CLASSE = PERSONAGENS.ID_CLASSE

SELECT * FROM PERSONAGENS
RIGHT JOIN CLASSES ON PERSONAGENS.ID_CLASSE = CLASSES.ID_CLASSE

SELECT * FROM CLASSE_HABILIDADES
INNER JOIN CLASSES ON CLASSES.ID_CLASSE = CLASSE_HABILIDADES.ID_CLASSE
INNER JOIN HABILIDADES ON HABILIDADES.ID_HABILIDADE = CLASSE_HABILIDADES.ID_HABILIDADE

SELECT * FROM CLASSE_HABILIDADES
INNER JOIN HABILIDADES ON HABILIDADES.ID_HABILIDADE = CLASSE_HABILIDADES.ID_HABILIDADE
INNER JOIN CLASSES ON CLASSES.ID_CLASSE = CLASSE_HABILIDADES.ID_CLASSE

SELECT * FROM CLASSE_HABILIDADES
INNER JOIN HABILIDADES ON HABILIDADES.ID_HABILIDADE = CLASSE_HABILIDADES.ID_HABILIDADE
RIGHT JOIN CLASSES ON CLASSES.ID_CLASSE = CLASSE_HABILIDADES.ID_CLASSE