CREATE DATABASE SENAI_HROADS_TARDE

CREATE TABLE CLASSES(
	ID_CLASSE INT IDENTITY PRIMARY KEY
	,NOME_CLASSE VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE HABILIDADES(
	ID_HABILIDADE INT IDENTITY PRIMARY KEY
	,NOME_HABILIDADE VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE CLASSE_HABILIDADES(
	ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES(ID_CLASSE)
	,ID_HABILIDADE INT FOREIGN KEY REFERENCES HABILIDADES(ID_HABILIDADE)
);

CREATE TABLE PERSONAGENS(
	ID_PERSONAGEM INT IDENTITY PRIMARY KEY
	,NOME_PERSONAGEM VARCHAR(255) NOT NULL UNIQUE
	,ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES(ID_CLASSE)
	,CAPACIDADE_VIDA INT NOT NULL
	,CAPACIDADE_MANA INT
	,ATUALIZACAO DATETIME NOT NULL
	,DATA_CRIACAO DATETIME NOT NULL
);

CREATE TABLE TIPO_HABILIDADES(
	ID_TIPO INT IDENTITY PRIMARY KEY
	,NOME_TIPO VARCHAR(255) NOT NULL UNIQUE
);