INSERT INTO CLASSES
VALUES ('Bárbaro')
	   ,('Cruzado')
	   ,('Caçadora de Demônios')
	   ,('Monge')
	   ,('Necromante')
	   ,('Feiticeiro')
	   ,('Arcanista')

INSERT INTO TIPO_HABILIDADES
VALUES ('Ataque'),('Defesa'),('Cura'),('Magia')

INSERT INTO HABILIDADES(NOME_HABILIDADE,ID_TIPO)
VALUES ('Lança Mortal',1),('Escudo Supremo',2),('Recuperar Vida',3)

INSERT INTO CLASSE_HABILIDADES(ID_CLASSE,ID_HABILIDADE)
VALUES (1,1)
	   ,(1,2)
	   ,(2,2)
	   ,(3,1)
	   ,(4,3)
	   ,(4,2)
	   ,(6,3)

INSERT INTO PERSONAGENS(NOME_PERSONAGEM,ID_CLASSE,CAPACIDADE_VIDA,CAPACIDADE_MANA,ATUALIZACAO,DATA_CRIACAO)
VALUES ('DeuBug',1,100,80,GETDATE(),18/01/2018)

INSERT INTO PERSONAGENS(NOME_PERSONAGEM,ID_CLASSE,CAPACIDADE_VIDA,CAPACIDADE_MANA,ATUALIZACAO,DATA_CRIACAO)
VALUES ('BitBug',4,70,100,GETDATE(),17/03/2016)
	   ,('Fer8',7,75,60,GETDATE(),18/03/2018)